# Site settings
title: #FixLyndale
email: fixlyndale@gmail.com
description: We need a Lyndale Avenue that is safe and accessible for everyone.
baseurl: "/"
url: "https://fixlyndale.com" # the base hostname & protocol for your site

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/fixlyndale

# Build settings
markdown: kramdown
